// <auto-generated />
namespace Work_02.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StudentDbFirst : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentDbFirst));
        
        string IMigrationMetadata.Id
        {
            get { return "202304251030371_StudentDbFirst"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
